languageCode = "en"
languageName = "English"
weight = 1
title = "No Good Father"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "image/avatar.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "YAMASHITA, Takao"
  image = "img/avatar.png"
  headline = "The sound, old pond and frog jump into water."
  bio = "The giant turtle on which the world rests"
  links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
#     { bluesky = "https://bsky.app/profile/username" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
    { facebook = "https://facebook.com/ty0730" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
    { github = "https://github.com/ac1965ac1965" },
#     { gitlab = "https://gitlab.com/ac1965" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://ac1965.hashnode.dev" },
    { instagram = "https://instagram.com/ac1965" },
#     { itch-io = "https://ac1965.itch.io" },
#     { keybase = "https://keybase.io/ac1965" },
#     { kickstarter = "https://www.kickstarter.com/profile/ac1965" },
#     { lastfm = "https://lastfm.com/user/ac1965" },
#     { linkedin = "https://linkedin.com/in/ac1965" },
#     { mastodon = "https://mastodon.instance/@ac1965" },
#     { medium = "https://medium.com/ac1965" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/ac1965" },
#     { pinterest = "https://pinterest.com/ac1965" },
#     { reddit = "https://reddit.com/user/ac1965" },
#     { researchgate = "https://www.researchgate.net/profile/ac1965" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/ac1965" },
#     { soundcloud = "https://soundcloud.com/ac1965" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/ac1965" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/ac1965" },
#     { threads = "https://www.threads.net/@ac1965" },
#     { tiktok = "https://tiktok.com/@ac1965" },
#     { tumblr = "https://ac1965.tumblr.com" },
#     { twitch = "https://twitch.tv/ac1965" },
#     { twitter = "https://twitter.com/ac1965" },
    { x-twitter = "https://twitter.com/ac1965" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/ac1965" },
#     { ko-fi = "https://ko-fi.com/ac1965" },
  ]
